workflows:
  name: Wood App Android APK Build
  instance_type: mac_mini_m1
  max_build_duration: 60
  environment:
    flutter: stable
    xcode: stable
  triggering:
    events:
      - push
  scripts:
    - name: Unzip Project File
      script: |
        unzip project.zip
        cd flutter_application_1
    - name: Fetch Flutter Dependencies
      script: |
        cd flutter_application_1
        flutter pub get
    - name: Build Android APK
      script: |
        cd flutter_application_1
        flutter build apk --release
  artifacts:
    - flutter_application_1/build/app/outputs/flutter-apk/*.apk
